#!/usr/bin/perl
my $basedir;
BEGIN{
    $basedir = $0;
    $basedir =~ s%(.*)/[^/]+$%\1%;
}
use lib $basedir;

require kvm;

if ( ! defined $ARGV[0] ) {
    die usage("please specify vmname\n");
}
my $vmname = $ARGV[0];

my $arp = kvm::arplist();
my $ifs = kvm::iflist($vmname);

#print ips
while (($interface, $ifobj ) = each %$ifs) {
    $mac = $ifobj->{"mac"};
    if (exists $arp->{"$mac"}) {
	print  $arp->{"$mac"}->{"ip"} . "\n";
    }
}

sub usage(){
    my $msg = shift;
    my $usg = "Usage: $0 <vmname>\n";

    
    if (defined $msg) { 
	my $red = `tput setaf 1`;
	my $reset = `tput sgr 0`;

	if (chomp($msg) >0 ) {
	    $reset .= "\n";
	} else {
	    $msg .= "\n";
	}

	$usg .= $red;
	$usg .= "\n${red}Error: $msg" . $reset;
	

    }


    return $usg;
}
