#!/usr/bin/perl
my $basedir;
BEGIN{
    $basedir = $0;
    $basedir =~ s%(.*)/[^/]+$%\1%;
}
use lib $basedir;

require kvm;

my $kvms = kvm::list();

sub printkvm{
    my $kvm = shift;
    my $color = `tput setaf 1`; #red
    my $nocolor = `tput sgr0`; #reset
    if ( $kvm->{"state"} eq "running" ){
	$color = `tput setaf 2`; #green
    }
    print "${color}${vmname} [$kvm->{state}]$nocolor\n";
    foreach my $ip ($kvm->{"ips"}) {
	print "\t   ip: $ip\n";
    }
    while ( ($blkid, $src) = each $kvm->{"blklist"}){
	print "\t  $blkid: $src\n";
    }

}

while ( ($vmname, $kvm) = each %$kvms ){
    printkvm($kvm);
}

sub usage(){
    print "Usage: %0 \nkvmls\n";
}
